public static class Lvl4
{
    public static void ToCaps(System.Collections.Generic.List<Energizer.Energy> caps)
    {
        Energizer.Energy en = new Energizer.Energy();
        en = new Energizer.Energy();
        en.x = 17;
        en.y = 10;
        caps.Add(en);
        en = new Energizer.Energy();
        en.x = 18;
        en.y = 10;
        caps.Add(en);
        en = new Energizer.Energy();
        en.x = 19;
        en.y = 10;
        caps.Add(en);
        en = new Energizer.Energy();
        en.x = 20;
        en.y = 10;
        caps.Add(en);
        en = new Energizer.Energy();
        en.x = 21;
        en.y = 10;
        caps.Add(en);
        en = new Energizer.Energy();
        en.x = 22;
        en.y = 10;
        caps.Add(en);
        en = new Energizer.Energy();
        en.x = 23;
        en.y = 10;
        caps.Add(en);
        en = new Energizer.Energy();
        en.x = 24;
        en.y = 10;
        caps.Add(en);
        en = new Energizer.Energy();
        en.x = 25;
        en.y = 10;
        caps.Add(en);
        en = new Energizer.Energy();
        en.x = 26;
        en.y = 10;
        caps.Add(en);
        en = new Energizer.Energy();
        en.x = 27;
        en.y = 10;
        caps.Add(en);
        en = new Energizer.Energy();
        en.x = 28;
        en.y = 10;
        caps.Add(en);
        en = new Energizer.Energy();
        en.x = 29;
        en.y = 10;
        caps.Add(en);
        en = new Energizer.Energy();
        en.x = 30;
        en.y = 10;
        caps.Add(en);
        en = new Energizer.Energy();
        en.x = 31;
        en.y = 10;
        caps.Add(en);
        en = new Energizer.Energy();
        en.x = 32;
        en.y = 10;
        caps.Add(en);
        en = new Energizer.Energy();
        en.x = 33;
        en.y = 10;
        caps.Add(en);
        en = new Energizer.Energy();
        en.x = 34;
        en.y = 10;
        caps.Add(en);
        en = new Energizer.Energy();
        en.x = 35;
        en.y = 10;
        caps.Add(en);
        en = new Energizer.Energy();
        en.x = 36;
        en.y = 10;
        caps.Add(en);
        en = new Energizer.Energy();
        en.x = 37;
        en.y = 10;
        caps.Add(en);
        en = new Energizer.Energy();
        en.x = 38;
        en.y = 10;
        caps.Add(en);
        en = new Energizer.Energy();
        en.x = 39;
        en.y = 10;
        caps.Add(en);
        en = new Energizer.Energy();
        en.x = 22;
        en.y = 11;
        caps.Add(en);
        en = new Energizer.Energy();
        en.x = 22;
        en.y = 12;
        caps.Add(en);
        en = new Energizer.Energy();
        en.x = 22;
        en.y = 13;
        caps.Add(en);
        en = new Energizer.Energy();
        en.x = 22;
        en.y = 14;
        caps.Add(en);
        en = new Energizer.Energy();
        en.x = 22;
        en.y = 15;
        caps.Add(en);
        en = new Energizer.Energy();
        en.x = 22;
        en.y = 16;
        caps.Add(en);
        en = new Energizer.Energy();
        en.x = 22;
        en.y = 17;
        caps.Add(en);
        en = new Energizer.Energy();
        en.x = 22;
        en.y = 18;
        caps.Add(en);
        en = new Energizer.Energy();
        en.x = 22;
        en.y = 19;
        caps.Add(en);
        en = new Energizer.Energy();
        en.x = 22;
        en.y = 20;
        caps.Add(en);
        en = new Energizer.Energy();
        en.x = 22;
        en.y = 21;
        caps.Add(en);
        en = new Energizer.Energy();
        en.x = 22;
        en.y = 22;
        caps.Add(en);
        en = new Energizer.Energy();
        en.x = 22;
        en.y = 23;
        caps.Add(en);
        en = new Energizer.Energy();
        en.x = 22;
        en.y = 24;
        caps.Add(en);
        en = new Energizer.Energy();
        en.x = 22;
        en.y = 25;
        caps.Add(en);
        en = new Energizer.Energy();
        en.x = 22;
        en.y = 26;
        caps.Add(en);
        en = new Energizer.Energy();
        en.x = 22;
        en.y = 27;
        caps.Add(en);
        en = new Energizer.Energy();
        en.x = 22;
        en.y = 28;
        caps.Add(en);
        en = new Energizer.Energy();
        en.x = 22;
        en.y = 29;
        caps.Add(en);
        en = new Energizer.Energy();
        en.x = 23;
        en.y = 11;
        caps.Add(en);
        en = new Energizer.Energy();
        en.x = 24;
        en.y = 13;
        caps.Add(en);
        en = new Energizer.Energy();
        en.x = 25;
        en.y = 15;
        caps.Add(en);
        en = new Energizer.Energy();
        en.x = 26;
        en.y = 17;
        caps.Add(en);
        en = new Energizer.Energy();
        en.x = 27;
        en.y = 19;
        caps.Add(en);
        en = new Energizer.Energy();
        en.x = 28;
        en.y = 21;
        caps.Add(en);
        en = new Energizer.Energy();
        en.x = 29;
        en.y = 23;
        caps.Add(en);
        en = new Energizer.Energy();
        en.x = 30;
        en.y = 25;
        caps.Add(en);
        en = new Energizer.Energy();
        en.x = 31;
        en.y = 27;
        caps.Add(en);
        en = new Energizer.Energy();
        en.x = 32;
        en.y = 29;
        caps.Add(en);
        en = new Energizer.Energy();
        en.x = 33;
        en.y = 27;
        caps.Add(en);
        en = new Energizer.Energy();
        en.x = 34;
        en.y = 25;
        caps.Add(en);
        en = new Energizer.Energy();
        en.x = 35;
        en.y = 23;
        caps.Add(en);
        en = new Energizer.Energy();
        en.x = 36;
        en.y = 21;
        caps.Add(en);
        en = new Energizer.Energy();
        en.x = 37;
        en.y = 19;
        caps.Add(en);
        en = new Energizer.Energy();
        en.x = 38;
        en.y = 17;
        caps.Add(en);
        en = new Energizer.Energy();
        en.x = 39;
        en.y = 15;
        caps.Add(en);
        en = new Energizer.Energy();
        en.x = 40;
        en.y = 13;
        caps.Add(en);
        en = new Energizer.Energy();
        en.x = 41;
        en.y = 11;
        caps.Add(en);
        en = new Energizer.Energy();
        en = new Energizer.Energy();
        en.x = 17;
        en.y = 30;
        caps.Add(en);
        en = new Energizer.Energy();
        en.x = 18;
        en.y = 30;
        caps.Add(en);
        en = new Energizer.Energy();
        en.x = 19;
        en.y = 30;
        caps.Add(en);
        en = new Energizer.Energy();
        en.x = 20;
        en.y = 30;
        caps.Add(en);
        en = new Energizer.Energy();
        en.x = 21;
        en.y = 30;
        caps.Add(en);
        en = new Energizer.Energy();
        en.x = 22;
        en.y = 30;
        caps.Add(en);
        en = new Energizer.Energy();
        en.x = 23;
        en.y = 30;
        caps.Add(en);
        en = new Energizer.Energy();
        en.x = 24;
        en.y = 30;
        caps.Add(en);
        en = new Energizer.Energy();
        en.x = 25;
        en.y = 30;
        caps.Add(en);
        en = new Energizer.Energy();
        en.x = 26;
        en.y = 30;
        caps.Add(en);
        en = new Energizer.Energy();
        en.x = 27;
        en.y = 30;
        caps.Add(en);
        en = new Energizer.Energy();
        en.x = 28;
        en.y = 30;
        caps.Add(en);
        en = new Energizer.Energy();
        en.x = 29;
        en.y = 30;
        caps.Add(en);
        en = new Energizer.Energy();
        en.x = 30;
        en.y = 30;
        caps.Add(en);
        en = new Energizer.Energy();
        en.x = 31;
        en.y = 30;
        caps.Add(en);
        en = new Energizer.Energy();
        en.x = 32;
        en.y = 30;
        caps.Add(en);
        en = new Energizer.Energy();
        en.x = 33;
        en.y = 30;
        caps.Add(en);
        en = new Energizer.Energy();
        en.x = 34;
        en.y = 30;
        caps.Add(en);
        en = new Energizer.Energy();
        en.x = 35;
        en.y = 30;
        caps.Add(en);
        en = new Energizer.Energy();
        en.x = 36;
        en.y = 30;
        caps.Add(en);
        en = new Energizer.Energy();
        en.x = 37;
        en.y = 30;
        caps.Add(en);
        en = new Energizer.Energy();
        en.x = 38;
        en.y = 30;
        caps.Add(en);
        en = new Energizer.Energy();
        en.x = 39;
        en.y = 30;
        caps.Add(en);
    }
}